stages:
  - deploy

deploy_to_server:
  stage: deploy
  image: ubuntu:latest
  only:
    - master
  variables:
    SSH_PRIVATE_KEY: $SSH_KEY
#  before_script:
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/kenji_first_rsa
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/kenji_first_rsa
    - cat ~/.ssh/kenji_first_rsa
